title: Charlie Huemmler # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently in the Masters of Urban Spatial Analytics program at 
  the University of Pennslyvania Weitzman School of Design, focusing on economic
  development and sustainable transportation. The skills I am learning are designed
  to modernize the data capabilites of any public or non-profit institution. I love 
  Philadelphia and am a strong advocate of public transit and micromobility infrastructure.
  <br><br>
  <a href=".pdf/resume.pdf"> Download my resume here
  <br>
  Other contacts:
  <a href="https://www.twitter.com/chuembucket">Twitter</a> <br>
  <a href="https://www.linkedin.com/in/charleshuemmler/">LinkedIn</a> <br>
  <a href="https://www.strava.com/athletes/6928466">Strava</a> <br> <br>

  
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
