title: Charlie Huemmler # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  he/him <br>
  cchuemmler@gmail.com
  <a href="https://www.twitter.com/chuembucket"> <img src="/images/twitter.png" width = 10 height = 10> </a> 
  <a href="https://www.linkedin.com/in/charleshuemmler/"> <img src="/images/twitter.png"> </a> 
  <a href="https://www.strava.com/athletes/6928466"> <img src="/images/twitter.png"> </a> <br>

  <a href=".pdf/resume.pdf"> Resume Download</a>

  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
